SOF-2298: Synchronize-only ingest flow
tv2/sofie-server pull request #247
Opened 2024-10-08 12:56 UTC by KvelaGorrrrnio

_**Note:** For the web client to behave correctly, the PR https://github.com/tv2/sofie-web-client/pull/272 is needed._

The PR introduces a new approach for handling ingest events observed through MongoDB that Sofie Core generates.

The approach used is to analyze the entire state of a rundown, when a sequence of observed ingest events for the rundown (or more rundowns) ends. By doing it this way, the code that runs at startup to ensure correct state and the code that runs when ingest events are received is the same.

The code analyzes the ingest data for the rundown against the existing rundown and classifies any changes to the rundown metadata, along with create, update and delete for segments and parts.

If a segment is affected (created, updated or deleted), then part changes under that segment is ignored, since the segment includes the new state of the parts. So the part changes are redundant and will most likely throw errors, when applied to the rundown - e.g. adding a part that is already there from the segment update.

One of the trickiest parts regarding handling ingest events from Sofie Core is to properly manage changes for on air segments and parts. The way changes to an on air segment is handled is by allowing all changes, since they are metadata changes.
Deleting an on air part results in an unsynced on air part, and an update results in an unsynced on air part, followed by a synced version of the part that will receive future updates.

To determine whether a part is updated or not, `EntityChangeDetector` is used, where all relevant attributes are compared. Complex objects are stringified and key-value pairs with the key `id` is removed. The removal of `id` attributes is because random ids were generated for sisyfos layers for each ingest, so a fixed amount of parts would always be detected as changed.

2024-10-09 11:28 UTC, LindvedKrvang commented on src/model/entities/test/entity-test-factory.ts
> +      isPlanned: true,
Remember to dobbeltcheck that this doesn't break any existing tests

2024-10-09 20:10 UTC, KvelaGorrrrnio commented on src/model/entities/test/entity-test-factory.ts
> +      isPlanned: true,
What should I test besides running the tests? :)

2024-10-10 08:03 UTC, RasmusAlbrektsen approved these changes

2024-10-10 08:03 UTC, RasmusAlbrektsen commented on src/business-logic/services/ingest-data-change-service.ts
> +  private emitEventsFromRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult, deletedSegmentsInfo: readonly DeletedSegmentInfo[], deletedPartsInfo: readonly D
These parameter are not nice to read :-D 
Maybe we should consider a different way of showing them and add it to linting?

2024-10-10 08:03 UTC, RasmusAlbrektsen commented on src/business-logic/services/ingest-data-change-service.ts
> +  private emitEventsFromRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult, deletedSegmentsInfo: readonly DeletedSegmentInfo[], deletedPartsInfo: readonly D
Generally the line length we allow is a bit much.

2024-10-10 08:03 UTC, RasmusAlbrektsen commented on src/model/entities/part.ts
> +  private doesPiecesOverlap(pieceA: Piece, pieceB: Piece): boolean {
Personal opinion: 
I'm not a fan of how `does` is making it in when it isn't grammatically correct, in this case it would be `do`. I understand that we are used to doing certain things when naming boolean return functions.

2024-10-11 05:45 UTC, LindvedKrvang commented on src/model/entities/test/entity-test-factory.ts
> +      isPlanned: true,
![image](https://github.com/user-attachments/assets/93483c20-70ca-442e-a14f-22271ad3bca3)

2024-10-11 06:07 UTC, LindvedKrvang requested changes
The request changes is only for making sure this PR isn't merged until we are certain that your `removeOverlappingPiecesOnSameLayer()` doesn't create unintended sideeffects

2024-10-11 06:07 UTC, LindvedKrvang commented on src/business-logic/services/ingest-data-change-service.ts
> +  private applyRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult): { deletedPartsInfo: DeletedPartInfo[], deletedSegmentsInfo: DeletedSegmentInfo[] } {
You have a nice `DeletedInfo` type that you can use here :)

2024-10-11 06:07 UTC, LindvedKrvang commented on src/business-logic/services/ingest-data-change-service.ts
> +  private emitEventsFromRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult, deletedSegmentsInfo: readonly DeletedSegmentInfo[], deletedPartsInfo: readonly D
The last two parameters can be combine in the type `DeletedInfo`.

2024-10-11 06:07 UTC, LindvedKrvang commented on src/business-logic/services/ingest-rundown-synchronizer.ts
> +  public getUpdatedSegments(segments: readonly Segment[], ingestedSegments: readonly IngestedSegment[]): readonly Segment[] {
Should be private

2024-10-11 06:07 UTC, LindvedKrvang commented on src/business-logic/services/ingest-rundown-synchronizer.ts
> +  public getDeletedSegments(segments: readonly Segment[], ingestedSegments: readonly IngestedSegment[]): readonly Segment[] {
Should be private

2024-10-11 06:07 UTC, LindvedKrvang commented on src/model/entities/part.ts
> +      this.removeOverlappingPiecesOnSameLayer(unPlannedPiece)
I'm quite sure this is going to have unintended side-effects i.e. wrong Piece behaviour. What does this have to do with the synchronize ingest flow?

2024-10-11 06:07 UTC, LindvedKrvang commented on src/model/entities/rundown.ts
> +    }
Is this to make the Unsynced copi of the OnAir Part be the one the Cursor is referencing? I.e. the update you did to `Segment.removePart()`?

2024-10-11 07:06 UTC, LindvedKrvang approved these changes

2024-10-11 08:52 UTC, KvelaGorrrrnio commented on src/business-logic/services/ingest-data-change-service.ts
> +  private emitEventsFromRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult, deletedSegmentsInfo: readonly DeletedSegmentInfo[], deletedPartsInfo: readonly D
I have used `DeletedInfo` instead.

2024-10-11 08:57 UTC, KvelaGorrrrnio commented on src/model/entities/part.ts
> +  private doesPiecesOverlap(pieceA: Piece, pieceB: Piece): boolean {
I agree. I have updated it to `doPiecesOverlap`.

2024-10-11 08:59 UTC, KvelaGorrrrnio commented on src/business-logic/services/ingest-data-change-service.ts
> +  private applyRundownSynchronizeResult(rundown: Rundown, rundownSynchronizeResult: RundownSynchronizeResult): { deletedPartsInfo: DeletedPartInfo[], deletedSegmentsInfo: DeletedSegmentInfo[] } {
Updated :)

2024-10-11 09:39 UTC, KvelaGorrrrnio commented on src/business-logic/services/ingest-rundown-synchronizer.ts
> +  public getUpdatedSegments(segments: readonly Segment[], ingestedSegments: readonly IngestedSegment[]): readonly Segment[] {
Updated :)

2024-10-11 09:39 UTC, KvelaGorrrrnio commented on src/business-logic/services/ingest-rundown-synchronizer.ts
> +  public getDeletedSegments(segments: readonly Segment[], ingestedSegments: readonly IngestedSegment[]): readonly Segment[] {
Updated :)

2024-10-11 09:40 UTC, KvelaGorrrrnio commented on src/model/entities/part.ts
> +      this.removeOverlappingPiecesOnSameLayer(unPlannedPiece)
I don't see any current use cases where this will have any problems. But it is worth having in mind going forward :+1:

2024-10-11 09:41 UTC, KvelaGorrrrnio commented on src/model/entities/rundown.ts
> +    }
It is :)

2024-10-11 09:51 UTC, LindvedKrvang approved these changes

2024-10-11 09:52 UTC, RasmusAlbrektsen approved these changes
LGTM

2024-10-11 09:53 UTC, merged